import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import { ConnectButton } from '@rainbow-me/rainbowkit';
import image from '../public/25.png';
import { ethers } from 'ethers';
import JSON from './ABI/MintJacques.JSON';
import { useEffect } from 'react';
import { useState } from 'react';







export default function Home() {
  const [error, setError] = useState('');
  const [data, setData] = useState({});
  const [loading, setLoading] = useState(false);

  const contractAddress = '0x0d93A85Af55F55D08B35A52c1078BAF580610a0F';


  async function getData() {
    if(typeof window.ethereum !== 'undefined') {
      const provider = new ethers.providers.Web3Provider(window.ethereum);
      const contract = new ethers.Contract(contractAddress, JSON.abi, provider);
      try {
        const cost = await contract.cost();
        const totalSupply = await contract.totalSupply();
        const object = {"cost": String(cost), "totalSupply": String(totalSupply)};
        setData(object);
        setLoading(true);
      }
      catch(err){
        setError(err.message);
      }
  }
}

  async function mint() {
    if(typeof window.ethereum !== 'undefined') {
      let accounts = await window.ethereum.request({ method: 'eth_requestAccounts' });
      const provider = new ethers.providers.Web3Provider(window.ethereum);
      const signer = provider.getSigner();
      const contract = new ethers.Contract(contractAddress, JSON.abi, signer);
      try {
        let overrides = {
          from: accounts[0],
          value: data.cost,
        }
        const tx = await contract.mint(accounts[0], 1, overrides);
        await transaction.wait();
        getData();
      }
      catch{
        setError(err.message);
      }
  }
  }
  useEffect(() => {
    getData();
  });
  return (
   
    <div className={styles.container}>
      <Head>
        <title>JP Nfts</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.header}>
            <ConnectButton />
        </div>
      </main>
      <div className={styles.mainContent}>
        <div className={styles.right}>
            <div className={styles.text}>
              <p className={styles.self}>Self Made Man</p>
              <h1>Jacques Picon NFT</h1>
              {loading && <p className={styles.minted}>Already {data.totalSupply} / 33 minted</p>}
              <p className={styles.pronoia}>Pronoia: The opposite of paranoia where someone believes that
the<br /> universe conspires in his favour.</p>
            </div>
        </div>
        <div className={styles.image}>
            <Image
              src={image}
              alt="Picture of the goat"
              width={500}
              height={500}
              priority
            />
            <p>No use, no doubt</p>
        </div>
      </div>
      <div className={styles.buttonContainer}>
            <button className={styles.button1} onClick={mint}>Click To Mint</button>
            <a href="https://testnets.opensea.io/collection/jacques-picon" target="_blank" rel="noreferrer"><button className={styles.button2}>OpenSea</button></a>
        </div>
    </div>
  )
}